name = "stock-arbitrage-manager-api"
main = "src/app.ts"
compatibility_date = "2024-10-27"
compatibility_flags = [
    "nodejs_compat",
    "nodejs_compat_populate_process_env"
]

[vars]
APP_NAME = "hono api"

[dev]
ip = "0.0.0.0"
port = 8788
